model:
  type: "nano"
  num_classes: 80

datasets:
  info:
    - 
      name: "coco"
      train_image_directory: "datasets/coco/images/train2017"
      train_label_path: "datasets/coco/annotations/instances_train2017.json"
      val_image_directory: "datasets/coco/images/val2017"
      val_label_path: "datasets/coco/annotations/instances_val2017.json"
      delete_iscrowd_image: True # iscrowd: Whether the image contains multiple objects
    -
      name: "custom"
      image_dir: ""
      label_path: ""
      
  num_workers: 0
  input_height: 640
  input_width: 640
  mosaic: 0.5 # image mosaic (probability)
  mix_up: 0.5 # image mix-up (probability)
  flip_ud: 0.5 # image flip up-down (probability)
  flip_lr: 0.5 # image flip left-right (probability)
  hsv_h: 0.015 # image HSV-Hue augmentation (fraction)
  hsv_s: 0.7 # image HSV-Saturation augmentation (fraction)
  hsv_v: 0.4 # image HSV-Value augmentation (fraction)

training:
  seed: 42
  total_epochs: 300
  batch_size: 32
  min_lr: 0.0001 # initial learning rate
  max_lr: 0.01 # maximum learning rate
  momentum: 0.937 # SGD momentum/Adam beta1
  weight_decay: 0.0005 # optimizer weight decay
  warmup_epochs: 5 # warmup epochs
  box: 7.5 # box loss gain
  cls: 0.5 # cls loss gain
  dfl: 1.5 # dfl loss gain
  save_dir: "./outputs"